'use client';
import { checkIsPublicRoute } from "@/functions/check-is-public-route";
import { usePathname } from "next/navigation"

export const metadata = {
  title: 'Next.js',
  description: 'Generated by Next.js',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {

  const pathname = usePathname();
  const isPublicPage = checkIsPublicRoute(pathname)

  return (
    <>
      {children}
    </>
  )
}
